# Generated by Django 4.0.3 on 2022-05-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_optionslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionslist',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='optionslist',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='optionslist',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
