# Generated by Django 4.0.3 on 2022-05-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('courses', '0004_rename_group_id_optionslist_group_and_more'),
  ]

  operations = [
    migrations.AddField(
      model_name='optionslist',
      name='courses',
      field=models.ManyToManyField(related_name='course', to='courses.course'),
    ),
  ]
