# Generated by Django 4.0.3 on 2022-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_optionslist_semester_optionslist_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionslist',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='courses.course'),
        ),
    ]
