# Generated by Django 4.0.3 on 2022-05-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_optionslist_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionslist',
            old_name='group',
            new_name='data',
        ),
    ]
