# Generated by Django 4.0.3 on 2022-05-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_group_optionslist_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionslist',
            old_name='data',
            new_name='category',
        ),
    ]
