# Generated by Django 4.0.3 on 2022-05-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_studentoptionchoice_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentoptionchoice',
            name='unique_migration_student_options_list_course_order',
        ),
        migrations.AddConstraint(
            model_name='studentoptionchoice',
            constraint=models.UniqueConstraint(fields=('student', 'options_list', 'course'), name='unique_migration_student_options_list_course'),
        ),
        migrations.AddConstraint(
            model_name='studentoptionchoice',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_migration_course_order'),
        ),
    ]
