# Generated by Django 4.0.3 on 2022-05-22 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_studentoptionchoice_unique_migration_student_options_list_course_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentoptionchoice',
            name='unique_migration_course_order',
        ),
        migrations.AlterField(
            model_name='studentoptionchoice',
            name='order',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
