# Generated by Django 4.0.3 on 2022-05-22 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_studentoptionchoice_unique_migration_course_order_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentoptionchoice',
            managers=[
                ('choices', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='studentoptionchoice',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='studentoptionchoice',
            constraint=models.UniqueConstraint(fields=('student', 'order'), name='unique_migration_student_order'),
        ),
    ]
