# Generated by Django 4.0.3 on 2022-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_studentoptionchoice_managers_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentoptionchoice',
            name='unique_migration_student_order',
        ),
        migrations.AddConstraint(
            model_name='studentoptionchoice',
            constraint=models.UniqueConstraint(fields=('options_list', 'order'), name='unique_migration_options_list_order'),
        ),
    ]
