# Generated by Django 4.0.4 on 2022-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_student_options_lists_user_changed_password_and_more'),
        ('courses', '0017_studentcourses_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionslist',
            name='students',
            field=models.ManyToManyField(related_name='students', to='users.student'),
        ),
    ]
