# Generated by Django 4.0.3 on 2022-05-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_grade_unique_migration_grade_student_year'),
        ('courses', '0018_optionslist_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourses',
            new_name='StudentCourse',
        ),
    ]
