# Generated by Django 4.0.4 on 2022-05-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_studentcourses_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionslist',
            name='degree',
            field=models.TextField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='optionslist',
            name='domain',
            field=models.TextField(choices=[('INFO', 'Info'), ('CTI', 'Cti'), ('MATE', 'Mate')], null=True),
        ),
        migrations.AlterField(
            model_name='optionslist',
            name='learning_mode',
            field=models.TextField(choices=[('IF', 'If'), ('IFR', 'Ifr'), ('ID', 'Id')], null=True),
        ),
        migrations.AlterField(
            model_name='optionslist',
            name='study_program',
            field=models.TextField(choices=[('NLP', 'Nlp'), ('DS', 'Ds'), ('SLA', 'Sla'), ('SD', 'Sd'), ('IA', 'Ia'), ('IS', 'Is'), ('BDTS', 'Bdts'), ('PSFS', 'Psfs'), ('MD', 'Md'), ('ASM', 'Asm'), ('TI', 'Ti'), ('INFO', 'Info'), ('MATEINFO', 'Mateinfo'), ('MATE', 'Mate'), ('MA', 'Ma')], null=True),
        ),
    ]
