# Generated by Django 4.0.4 on 2022-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_student_degree_alter_student_domain_and_more'),
        ('courses', '0020_alter_optionslist_degree_alter_optionslist_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_students', to='users.student'),
        ),
    ]
