# Generated by Django 4.0.4 on 2022-06-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
