# Generated by Django 4.0.4 on 2022-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_role_alter_user_verified'),
        ('courses', '0022_remove_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_students', to='users.student'),
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
