# Generated by Django 4.0.4 on 2022-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_semester_alter_course_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='optionslist',
            options={'verbose_name': 'options list', 'verbose_name_plural': 'options lists'},
        ),
        migrations.AlterModelOptions(
            name='studentoptionchoice',
            options={'verbose_name': 'student option choice', 'verbose_name_plural': 'student option choices'},
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.TextField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], null=True),
        ),
    ]
