# Generated by Django 4.0.4 on 2022-08-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_optionslist_study_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
    ]
