# Generated by Django 4.0.4 on 2022-08-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_teacher_user'),
        ('courses', '0028_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='users.teacher'),
        ),
    ]
