# Generated by Django 4.0.4 on 2022-08-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.TextField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], null=True),
        ),
    ]
