# Generated by Django 4.0.3 on 2022-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('users', '0005_group'),
  ]

  operations = [
    migrations.AddField(
      model_name='user',
      name='verified',
      field=models.BooleanField(default=True, verbose_name='verified'),
    ),
  ]
