# Generated by Django 4.0.3 on 2022-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('users', '0007_remove_student_degree_remove_student_domain_and_more'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='group',
      name='semester',
    ),
    migrations.RemoveField(
      model_name='group',
      name='year',
    ),
    migrations.AlterField(
      model_name='user',
      name='email',
      field=models.EmailField(max_length=254, unique=True),
    ),
    migrations.AlterField(
      model_name='user',
      name='first_name',
      field=models.TextField(max_length=50),
    ),
    migrations.AlterField(
      model_name='user',
      name='last_name',
      field=models.TextField(max_length=50),
    ),
  ]
