# Generated by Django 4.0.3 on 2022-05-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_data_optionslist_category'),
        ('users', '0009_rename_group_data_rename_group_student_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='data',
            new_name='category',
        ),
    ]
