# Generated by Django 4.0.4 on 2022-05-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ('courses', '0017_studentcourses_alter_course_title_and_more'),
    ('users', '0013_remove_student_category_and_more'),
  ]

  operations = [
    migrations.AddField(
      model_name='student',
      name='options_lists',
      field=models.ManyToManyField(related_name='options_lists', to='courses.optionslist'),
    ),
    migrations.AddField(
      model_name='user',
      name='changed_password',
      field=models.BooleanField(default=False),
    ),
    migrations.AlterField(
      model_name='grade',
      name='student',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student'),
    ),
    migrations.AlterField(
      model_name='user',
      name='verified',
      field=models.BooleanField(default=True),
    ),
  ]
