# Generated by Django 4.0.4 on 2022-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('courses', '0024_course_semester_alter_course_capacity'),
    ('users', '0021_alter_user_role_alter_user_verified'),
  ]

  operations = [
    migrations.AddField(
      model_name='student',
      name='courses',
      field=models.ManyToManyField(related_name='student_courses', to='courses.course'),
    ),
  ]
