# Generated by Django 4.0.4 on 2022-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_appsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='id',
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='key',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
