# Generated by Django 4.0.4 on 2022-07-05 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_appsetting_id_alter_appsetting_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(choices=[('INFO', 'Info'), ('CTI', 'Cti'), ('MATE', 'Mate')], null=True)),
                ('learning_mode', models.TextField(choices=[('IF', 'If'), ('IFR', 'Ifr'), ('ID', 'Id')], null=True)),
                ('degree', models.TextField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], null=True)),
                ('study_program', models.TextField(choices=[('NLP', 'Nlp'), ('DS', 'Ds'), ('SLA', 'Sla'), ('SD', 'Sd'), ('IA', 'Ia'), ('IS', 'Is'), ('BDTS', 'Bdts'), ('PSFS', 'Psfs'), ('MD', 'Md'), ('ASM', 'Asm'), ('TI', 'Ti'), ('INFO', 'Info'), ('MATEINFO', 'Mateinfo'), ('MATE', 'Mate'), ('MA', 'Ma')], null=True)),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('SECRETARY', 'Secretary'), ('ADMIN', 'Admin')], null=True),
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='responsible_for_categories', to='users.category')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.category'),
        ),
    ]
