# Generated by Django 4.0.4 on 2022-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_category_alter_user_role_secretary_student_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
        migrations.AlterModelOptions(
            name='secretary',
            options={'verbose_name': 'secretary', 'verbose_name_plural': 'secretaries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.TextField(choices=[('MATH', 'Math'), ('COMPUTER_SCIENCE', 'Computer Science')], null=True),
        ),
    ]
