# Generated by Django 4.0.4 on 2022-08-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_category_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='study_program',
        ),
    ]
