# Generated by Django 4.0.4 on 2022-08-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_category_unique_migration_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AlterField(
            model_name='student',
            name='study_program',
            field=models.TextField(choices=[('NLP', 'Nlp'), ('DS', 'Ds'), ('SAL', 'Sal'), ('AMA', 'Ama'), ('SD', 'Sd'), ('AI', 'Ai'), ('IS', 'Is'), ('BDTS', 'Bdts'), ('PSFS', 'Psfs'), ('MD', 'Md'), ('ASM', 'Asm'), ('TI', 'Ti'), ('INFO', 'Info'), ('MATEINFO', 'Mateinfo'), ('MATE', 'Mate'), ('MA', 'Ma')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], null=True),
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
    ]
