# Generated by Django 4.0.4 on 2022-08-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_teacher_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
